name: contatos_dio
description: Aplicativo de cadastro de contatos para o bootcamp Santander 2023 da DIO
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  provider: ^6.0.5
  contact_auth_api:
    path: ./packages/contact_auth_api
  contact_auth_api_parse:
    path: ./packages/contact_auth_api_parse
  contact_api:
    path: ./packages/contact_api
  contact_api_parse:
    path: ./packages/contact_api_parse
  google_sign_in: ^6.1.5
  firebase_core: ^2.19.0
  flutter_dotenv: ^5.1.0
  equatable: ^2.0.5
  hydrated_bloc: ^9.1.2
  path_provider: ^2.1.1
  image_picker: ^1.0.4
  image_cropper: ^4.0.1
  google_fonts: ^4.0.4
  brasil_fields: ^1.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env